USE cric_shop_api;

DROP TABLE IF EXISTS lane;

CREATE TABLE lane (
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(128) NOT NULL,
	image VARCHAR(512) NULL,
	gallery TEXT NULL,
	short_description VARCHAR(1024) NULL,
	long_description VARCHAR(1024) NULL,
	rate DECIMAL(10,2) NOT NULL DEFAULT 0.0,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
	deleted_at TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;